"""Remove description from work_types

Revision ID: 64619729f440
Revises: e782e1b1289d
Create Date: 2026-01-10 21:56:08.255888

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64619729f440"
down_revision: Union[str, Sequence[str], None] = "e782e1b1289d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("work_types", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("work_types", sa.Column("description", sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
